apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cka-deploy
  name: cka-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cka-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cka-deploy
    spec:
      containers:
      - image: devopstitan/cka-exam:mysql-question-09
        name: cka-exam
        ports:
        - containerPort: 3306
        resources: {}
status: {}
