apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
spec:
  containers:
  - name: web-app
    image: busybox
    command: ["sh", "-c", "echo 'Web app container is running...'; sleep 3600"]
  initContainers:
  - name: init-container
    image: postgres
    command: ["sh", "-c", "until nc -zv $POSTGRES_HOST $POSTGRES_PORT; do echo 'Waiting for dependencies...'; sleep 5; done; echo 'Dependencies are ready'"]
    env:
    - name: POSTGRES_HOST
      value: db
    - name: POSTGRES_PORT
      value: "5432"
