apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-prod
  labels:
    app: mysql
    tier: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mysql
        tier: prod
    spec:
      containers:
      - image: mysql
        name: mysql
        ports:
        - containerPort: 80
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret